# Generated by Django 4.1.4 on 2022-12-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_owner_alter_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
