version: "3.8"

services:
  postgres:
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - django_core/django_core/.env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./dumps:/code/dumps

  backend:
    restart: always
    container_name: aes_django_core
    build: ./django_core
    command: bash -c "
      python manage.py migrate &&
      gunicorn -w 3 django_core.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./django_core:/django_core
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./django_core/media:/app/media