version: "3.3"

services:

  postgres:

    image: postgres:14.5

    ports:

      - "5432:5432"

    volumes:

      - ./data/postgresql:/var/lib/postgresql/data

      - ./dumps:/code/dumps

    env_file:

      - django_core/django_core/.env
