# Generated by Django 4.1.4 on 2022-12-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_alter_project_options_project_owner'),
        ('user_core', '0004_student_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_core.student')),
            ],
            options={
                'verbose_name': 'Заявка в проект',
                'verbose_name_plural': 'Заявки в проект',
            },
        ),
    ]
