# Generated by Django 4.1.4 on 2022-12-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='owner',
        ),
    ]
