# Generated by Django 4.1.4 on 2022-12-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', max_length=255, upload_to='profile_images')),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('about_me', models.CharField(blank=True, max_length=512, null=True)),
                ('work_places', models.CharField(blank=True, max_length=512, null=True)),
                ('education', models.CharField(blank=True, max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contacts', models.CharField(blank=True, max_length=128, null=True)),
                ('pet_projects', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='cv', to='tags.tag')),
            ],
        ),
    ]
