# Generated by Django 4.1.4 on 2022-12-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
