# Generated by Django 4.1.4 on 2022-12-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0001_initial'),
        ('cv', '0002_cv_about_me_cv_contacts_cv_education_cv_image_cv_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_core.student'),
        ),
        migrations.AddField(
            model_name='cv',
            name='work_places',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
