# Generated by Django 4.1.4 on 2022-12-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_company'),
        ('cv', '0003_cv_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='pet_projects',
        ),
        migrations.AddField(
            model_name='cv',
            name='pet_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='cv', to='projects.project'),
        ),
    ]
