# Generated by Django 4.1.4 on 2022-12-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_cv_pet_projects_cv_pet_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
    ]
