# Generated by Django 4.1.4 on 2022-12-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0002_company_is_premium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
