# Generated by Django 4.1.4 on 2022-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
