# Generated by Django 4.1.4 on 2022-12-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0004_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
